### ISSUE TITLE
运行失败

### ISSUE THREAD

**Issue by kof8855** [Secriy/CloudMusic-LevelUp#27]
==============================
Traceback (most recent call last):
  File "action.py", line 300, in <module>
    res_sign = app.sign()
  File "action.py", line 224, in sign
    return "签到失败 " + str(ret["code"]) + "：" + ret["message"]
TypeError: can only concatenate str (not "NoneType") to str

D:\Python\CloudMusic-LevelUp-master>

**Comment by kof8855** [comment]
可以了md5的值要小写的
