### ISSUE TITLE
github actions出错

### ISSUE THREAD

**Issue by qbyyy** [Secriy/CloudMusic-LevelUp#3]
`Run python3 action.py ${PHONE} ${PASSWORD} -s ${SCKEY}
==============================
Traceback (most recent call last):
  File "action.py", line 230, in <module>
    res_task = app.task(info['playlist'])
  File "action.py", line 184, in task
    }, random.sample(musicId, 420))))
  File "/opt/hostedtoolcache/Python/3.8.6/x64/lib/python3.8/random.py", line 363, in sample
    raise ValueError("Sample larger than population or is negative")
ValueError: Sample larger than population or is negative
Error: Process completed with exit code 1.`

**Comment by qbyyy** [comment]
Run python3 action.py ${PHONE} ${PASSWORD} -s ${SCKEY}
==============================
Traceback (most recent call last):
  File "action.py", line 230, in <module>
    res_task = app.task(info['playlist'])
  File "action.py", line 184, in task
    }, random.sample(musicId, 420))))
  File "/opt/hostedtoolcache/Python/3.8.6/x64/lib/python3.8/random.py", line 363, in sample
    raise ValueError("Sample larger than population or is negative")
ValueError: Sample larger than population or is negative
Error: Process completed with exit code 1.

**Comment by Secriy** [comment]
这个是由于网易云音乐给你推荐的歌单歌曲总数小于420导致的，一般情况下推荐的歌单都很大因此我没有考虑到过小的情况，现在已经修复，感谢反馈
