### ISSUE TITLE
关于无法执行刷播放量

### ISSUE THREAD

**Issue by Kurisutaru-s** [secriy/CloudMusic-LevelUp#72]
登录签到正常，但是刷播放量失败。
日志：
Traceback (most recent call last):
  File "/usr/lib/python3.6/site-packages/urllib3/connectionpool.py", line 600, in urlopen
    chunked=chunked)
  File "/usr/lib/python3.6/site-packages/urllib3/connectionpool.py", line 384, in _make_request
    six.raise_from(e, None)
  File "<string>", line 3, in raise_from
  File "/usr/lib/python3.6/site-packages/urllib3/connectionpool.py", line 380, in _make_request
    httplib_response = conn.getresponse()
  File "/usr/lib64/python3.6/http/client.py", line 1361, in getresponse
    response.begin()
  File "/usr/lib64/python3.6/http/client.py", line 311, in begin
    version, status, reason = self._read_status()
  File "/usr/lib64/python3.6/http/client.py", line 280, in _read_status
    raise RemoteDisconnected("Remote end closed connection without"
http.client.RemoteDisconnected: Remote end closed connection without response

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.6/site-packages/requests/adapters.py", line 449, in send
    timeout=timeout
  File "/usr/lib/python3.6/site-packages/urllib3/connectionpool.py", line 638, in urlopen
    _stacktrace=sys.exc_info()[2])
  File "/usr/lib/python3.6/site-packages/urllib3/util/retry.py", line 368, in increment
    raise six.reraise(type(error), error, _stacktrace)
  File "/usr/lib/python3.6/site-packages/urllib3/packages/six.py", line 692, in reraise
    raise value.with_traceback(tb)
  File "/usr/lib/python3.6/site-packages/urllib3/connectionpool.py", line 600, in urlopen
    chunked=chunked)
  File "/usr/lib/python3.6/site-packages/urllib3/connectionpool.py", line 384, in _make_request
    six.raise_from(e, None)
  File "<string>", line 3, in raise_from
  File "/usr/lib/python3.6/site-packages/urllib3/connectionpool.py", line 380, in _make_request
    httplib_response = conn.getresponse()
  File "/usr/lib64/python3.6/http/client.py", line 1361, in getresponse
    response.begin()
  File "/usr/lib64/python3.6/http/client.py", line 311, in begin
    version, status, reason = self._read_status()
  File "/usr/lib64/python3.6/http/client.py", line 280, in _read_status
    raise RemoteDisconnected("Remote end closed connection without"
urllib3.exceptions.ProtocolError: ('Connection aborted.', RemoteDisconnected('Remote end closed connection without response',))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "action.py", line 428, in <module>
    tasks_pool(get_args())
  File "action.py", line 423, in tasks_pool
    run_task(infos, phone_list[k], calc_md5(passwd_list[k]))
  File "action.py", line 402, in run_task
    res_task = app.task()
  File "action.py", line 363, in task
    self.get_task_musics(),
  File "action.py", line 338, in get_task_musics
    subscribe_musics = self.get_list_musics(self.get_subscribe_playlists())
  File "action.py", line 328, in get_list_musics
    headers=self.headers,
  File "/usr/local/lib/python3.6/site-packages/requests/sessions.py", line 578, in post
    return self.request('POST', url, data=data, json=json, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/requests/sessions.py", line 530, in request    resp = self.send(prep, **send_kwargs)
  File "/usr/local/lib/python3.6/site-packages/requests/sessions.py", line 643, in send
    r = adapter.send(request, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/requests/adapters.py", line 498, in send
    raise ConnectionError(err, request=request)
requests.exceptions.ConnectionError: ('Connection aborted.', RemoteDisconnected('Remote end closed connection without   response',))

**Comment by secriy** [comment]
@Kurisutaru-s 网络原因，请检查下是否是本地使用了代理影响了请求，建议在GitHub或使用腾讯云函数部署。

**Comment by Kurisutaru-s** [comment]
服务器在中国香港，是这个原因吗？

**Comment by secriy** [comment]
@Kurisutaru-s 这个我不清楚，可以尝试在本地执行对比结果，也可以在服务器上多次执行检查是否每次都会出现错误。

**Comment by Kurisutaru-s** [comment]
好的，我尝试用腾讯云函数搭建吧，谢谢

**Comment by Kurisutaru-s** [comment]
腾讯云执行返回以下结果

Traceback (most recent call last):\n  File \"/var/user/index.py\", line 18, in main_handler\n    action.tasks_pool(infos)\n  File \"/var/user/action.py\", line 440, in tasks_pool\n    run_task(infos, phone_list[k], calc_md5(passwd_list[k]))\n  File \"/var/user/action.py\", line 419, in run_task\n    res_task = app.task()\n  File \"/var/user/action.py\", line 380, in task\n    self.get_task_musics(),\n  File \"/var/user/action.py\", line 355, in get_task_musics\n    subscribe_musics = self.get_list_musics(self.get_subscribe_playlists())\n  File \"/var/user/action.py\", line 347, in get_list_musics\n    musics.extend([i[\"id\"] for i in ret[\"playlist\"][\"trackIds\"]])\nKeyError: 'playlist'","statusCode":430}

**Comment by secriy** [comment]
@Kurisutaru-s 你好，这可能是一个bug，请问你有没有收藏过歌单？

**Comment by Kurisutaru-s** [comment]
有收藏，收藏了约100个歌单

**Comment by secriy** [comment]
@Kurisutaru-s 可以把[355行](https://github.com/secriy/CloudMusic-LevelUp/blob/6e3c68788ff863d3c3d48960a50a6a88dc136e36/action.py#L355)和357行注释掉

**Comment by Kurisutaru-s** [comment]
好了，问题解决了，谢谢
